youtube-dl: use different playlist in test
The old playlist was no longer passing the test:

    [youtube] qDNPQo9UmJA: Downloading video info webpage
    ERROR: Watch this video on YouTube. Playback on other
           websites has been disabled by the video owner.